### PR TITLE
Updates for latest version of validator

### PR DESCRIPTION
**Pull request by alisonrclarke**

### CODE REVIEW

**Comment by alisonrclarke** [comment]
Need to update requirements.txt once the hepdata-converter pypi package is updated.

**Comment by alisonrclarke** [comment]
Need to update the pypi version in Dockerfile once @GraemeWatt has created a new pypi package for hepdata-converter-ws.

**Comment by GraemeWatt** [comment]
> Need to update the pypi version in Dockerfile once @GraemeWatt has created a new pypi package for hepdata-converter-ws.

Now done:
https://github.com/HEPData/hepdata-converter-ws/releases/tag/0.1.7
https://pypi.org/project/hepdata-converter-ws/0.1.7/

**Comment by alisonrclarke** [comment]
Includes remainder of fix for https://github.com/HEPData/hepdata-converter-ws/issues/12

**Review by GraemeWatt — APPROVED** [review]

**Pull request merged**
